version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env.production

  postgres:
    image: postgres:14.5
    container_name: postgresprisma
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.production
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-prisma-docker-db